/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package EmergencyRequestDB.model.impl;

import EmergencyRequestDB.model.EmergencyRequest;

import EmergencyRequestDB.service.EmergencyRequestLocalServiceUtil;

/**
 * The extended model base implementation for the EmergencyRequest service. Represents a row in the &quot;Fire_EmergencyRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmergencyRequestImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmergencyRequestImpl
 * @see EmergencyRequest
 * @generated
 */
public abstract class EmergencyRequestBaseImpl
	extends EmergencyRequestModelImpl implements EmergencyRequest {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a emergency request model instance should use the <code>EmergencyRequest</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			EmergencyRequestLocalServiceUtil.addEmergencyRequest(this);
		}
		else {
			EmergencyRequestLocalServiceUtil.updateEmergencyRequest(this);
		}
	}

}