/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package TicketMgmtDB.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TicketMgmt service. Represents a row in the &quot;ATS_TicketMgmt&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>TicketMgmtDB.model.impl.TicketMgmtModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>TicketMgmtDB.model.impl.TicketMgmtImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TicketMgmt
 * @generated
 */
@ProviderType
public interface TicketMgmtModel
	extends BaseModel<TicketMgmt>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ticket mgmt model instance should use the {@link TicketMgmt} interface instead.
	 */

	/**
	 * Returns the primary key of this ticket mgmt.
	 *
	 * @return the primary key of this ticket mgmt
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ticket mgmt.
	 *
	 * @param primaryKey the primary key of this ticket mgmt
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this ticket mgmt.
	 *
	 * @return the uuid of this ticket mgmt
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this ticket mgmt.
	 *
	 * @param uuid the uuid of this ticket mgmt
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the ticket_id of this ticket mgmt.
	 *
	 * @return the ticket_id of this ticket mgmt
	 */
	public long getTicket_id();

	/**
	 * Sets the ticket_id of this ticket mgmt.
	 *
	 * @param ticket_id the ticket_id of this ticket mgmt
	 */
	public void setTicket_id(long ticket_id);

	/**
	 * Returns the group ID of this ticket mgmt.
	 *
	 * @return the group ID of this ticket mgmt
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this ticket mgmt.
	 *
	 * @param groupId the group ID of this ticket mgmt
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this ticket mgmt.
	 *
	 * @return the company ID of this ticket mgmt
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ticket mgmt.
	 *
	 * @param companyId the company ID of this ticket mgmt
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this ticket mgmt.
	 *
	 * @return the user ID of this ticket mgmt
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this ticket mgmt.
	 *
	 * @param userId the user ID of this ticket mgmt
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this ticket mgmt.
	 *
	 * @return the user uuid of this ticket mgmt
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this ticket mgmt.
	 *
	 * @param userUuid the user uuid of this ticket mgmt
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this ticket mgmt.
	 *
	 * @return the user name of this ticket mgmt
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this ticket mgmt.
	 *
	 * @param userName the user name of this ticket mgmt
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this ticket mgmt.
	 *
	 * @return the create date of this ticket mgmt
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this ticket mgmt.
	 *
	 * @param createDate the create date of this ticket mgmt
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this ticket mgmt.
	 *
	 * @return the modified date of this ticket mgmt
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ticket mgmt.
	 *
	 * @param modifiedDate the modified date of this ticket mgmt
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the bus number of this ticket mgmt.
	 *
	 * @return the bus number of this ticket mgmt
	 */
	@AutoEscape
	public String getBusNumber();

	/**
	 * Sets the bus number of this ticket mgmt.
	 *
	 * @param busNumber the bus number of this ticket mgmt
	 */
	public void setBusNumber(String busNumber);

	/**
	 * Returns the from location of this ticket mgmt.
	 *
	 * @return the from location of this ticket mgmt
	 */
	@AutoEscape
	public String getFromLocation();

	/**
	 * Sets the from location of this ticket mgmt.
	 *
	 * @param fromLocation the from location of this ticket mgmt
	 */
	public void setFromLocation(String fromLocation);

	/**
	 * Returns the to location of this ticket mgmt.
	 *
	 * @return the to location of this ticket mgmt
	 */
	@AutoEscape
	public String getToLocation();

	/**
	 * Sets the to location of this ticket mgmt.
	 *
	 * @param toLocation the to location of this ticket mgmt
	 */
	public void setToLocation(String toLocation);

	/**
	 * Returns the journey date of this ticket mgmt.
	 *
	 * @return the journey date of this ticket mgmt
	 */
	public Date getJourneyDate();

	/**
	 * Sets the journey date of this ticket mgmt.
	 *
	 * @param journeyDate the journey date of this ticket mgmt
	 */
	public void setJourneyDate(Date journeyDate);

	/**
	 * Returns the seat number of this ticket mgmt.
	 *
	 * @return the seat number of this ticket mgmt
	 */
	public int getSeatNumber();

	/**
	 * Sets the seat number of this ticket mgmt.
	 *
	 * @param seatNumber the seat number of this ticket mgmt
	 */
	public void setSeatNumber(int seatNumber);

	/**
	 * Returns the fare amount of this ticket mgmt.
	 *
	 * @return the fare amount of this ticket mgmt
	 */
	public Long getFareAmount();

	/**
	 * Sets the fare amount of this ticket mgmt.
	 *
	 * @param fareAmount the fare amount of this ticket mgmt
	 */
	public void setFareAmount(Long fareAmount);

	@Override
	public TicketMgmt cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}