/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package OTP_DB.service.base;

import OTP_DB.model.SignUpOTP;

import OTP_DB.service.SignUpOTPLocalService;
import OTP_DB.service.persistence.SignUpOTPPersistence;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the sign up otp local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link OTP_DB.service.impl.SignUpOTPLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OTP_DB.service.impl.SignUpOTPLocalServiceImpl
 * @generated
 */
public abstract class SignUpOTPLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService, SignUpOTPLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>SignUpOTPLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>OTP_DB.service.SignUpOTPLocalServiceUtil</code>.
	 */

	/**
	 * Adds the sign up otp to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect SignUpOTPLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param signUpOTP the sign up otp
	 * @return the sign up otp that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public SignUpOTP addSignUpOTP(SignUpOTP signUpOTP) {
		signUpOTP.setNew(true);

		return signUpOTPPersistence.update(signUpOTP);
	}

	/**
	 * Creates a new sign up otp with the primary key. Does not add the sign up otp to the database.
	 *
	 * @param otpId the primary key for the new sign up otp
	 * @return the new sign up otp
	 */
	@Override
	@Transactional(enabled = false)
	public SignUpOTP createSignUpOTP(long otpId) {
		return signUpOTPPersistence.create(otpId);
	}

	/**
	 * Deletes the sign up otp with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect SignUpOTPLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param otpId the primary key of the sign up otp
	 * @return the sign up otp that was removed
	 * @throws PortalException if a sign up otp with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public SignUpOTP deleteSignUpOTP(long otpId) throws PortalException {
		return signUpOTPPersistence.remove(otpId);
	}

	/**
	 * Deletes the sign up otp from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect SignUpOTPLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param signUpOTP the sign up otp
	 * @return the sign up otp that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public SignUpOTP deleteSignUpOTP(SignUpOTP signUpOTP) {
		return signUpOTPPersistence.remove(signUpOTP);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return signUpOTPPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			SignUpOTP.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return signUpOTPPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>OTP_DB.model.impl.SignUpOTPModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return signUpOTPPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>OTP_DB.model.impl.SignUpOTPModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return signUpOTPPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return signUpOTPPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return signUpOTPPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public SignUpOTP fetchSignUpOTP(long otpId) {
		return signUpOTPPersistence.fetchByPrimaryKey(otpId);
	}

	/**
	 * Returns the sign up otp matching the UUID and group.
	 *
	 * @param uuid the sign up otp's UUID
	 * @param groupId the primary key of the group
	 * @return the matching sign up otp, or <code>null</code> if a matching sign up otp could not be found
	 */
	@Override
	public SignUpOTP fetchSignUpOTPByUuidAndGroupId(String uuid, long groupId) {
		return signUpOTPPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the sign up otp with the primary key.
	 *
	 * @param otpId the primary key of the sign up otp
	 * @return the sign up otp
	 * @throws PortalException if a sign up otp with the primary key could not be found
	 */
	@Override
	public SignUpOTP getSignUpOTP(long otpId) throws PortalException {
		return signUpOTPPersistence.findByPrimaryKey(otpId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(signUpOTPLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(SignUpOTP.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("otpId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			signUpOTPLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(SignUpOTP.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("otpId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(signUpOTPLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(SignUpOTP.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("otpId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<SignUpOTP>() {

				@Override
				public void performAction(SignUpOTP signUpOTP)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, signUpOTP);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(SignUpOTP.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return signUpOTPPersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement SignUpOTPLocalServiceImpl#deleteSignUpOTP(SignUpOTP) to avoid orphaned data");
		}

		return signUpOTPLocalService.deleteSignUpOTP((SignUpOTP)persistedModel);
	}

	@Override
	public BasePersistence<SignUpOTP> getBasePersistence() {
		return signUpOTPPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return signUpOTPPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the sign up otps matching the UUID and company.
	 *
	 * @param uuid the UUID of the sign up otps
	 * @param companyId the primary key of the company
	 * @return the matching sign up otps, or an empty list if no matches were found
	 */
	@Override
	public List<SignUpOTP> getSignUpOTPsByUuidAndCompanyId(
		String uuid, long companyId) {

		return signUpOTPPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of sign up otps matching the UUID and company.
	 *
	 * @param uuid the UUID of the sign up otps
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of sign up otps
	 * @param end the upper bound of the range of sign up otps (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching sign up otps, or an empty list if no matches were found
	 */
	@Override
	public List<SignUpOTP> getSignUpOTPsByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<SignUpOTP> orderByComparator) {

		return signUpOTPPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the sign up otp matching the UUID and group.
	 *
	 * @param uuid the sign up otp's UUID
	 * @param groupId the primary key of the group
	 * @return the matching sign up otp
	 * @throws PortalException if a matching sign up otp could not be found
	 */
	@Override
	public SignUpOTP getSignUpOTPByUuidAndGroupId(String uuid, long groupId)
		throws PortalException {

		return signUpOTPPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the sign up otps.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>OTP_DB.model.impl.SignUpOTPModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of sign up otps
	 * @param end the upper bound of the range of sign up otps (not inclusive)
	 * @return the range of sign up otps
	 */
	@Override
	public List<SignUpOTP> getSignUpOTPs(int start, int end) {
		return signUpOTPPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of sign up otps.
	 *
	 * @return the number of sign up otps
	 */
	@Override
	public int getSignUpOTPsCount() {
		return signUpOTPPersistence.countAll();
	}

	/**
	 * Updates the sign up otp in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect SignUpOTPLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param signUpOTP the sign up otp
	 * @return the sign up otp that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public SignUpOTP updateSignUpOTP(SignUpOTP signUpOTP) {
		return signUpOTPPersistence.update(signUpOTP);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			SignUpOTPLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		signUpOTPLocalService = (SignUpOTPLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return SignUpOTPLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return SignUpOTP.class;
	}

	protected String getModelClassName() {
		return SignUpOTP.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = signUpOTPPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected SignUpOTPLocalService signUpOTPLocalService;

	@Reference
	protected SignUpOTPPersistence signUpOTPPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		SignUpOTPLocalServiceBaseImpl.class);

}