/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package RoleManagementDB.model.impl;

import RoleManagementDB.model.RoleTable;

import RoleManagementDB.service.RoleTableLocalServiceUtil;

/**
 * The extended model base implementation for the RoleTable service. Represents a row in the &quot;fire_RoleTable&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RoleTableImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RoleTableImpl
 * @see RoleTable
 * @generated
 */
public abstract class RoleTableBaseImpl
	extends RoleTableModelImpl implements RoleTable {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a role table model instance should use the <code>RoleTable</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			RoleTableLocalServiceUtil.addRoleTable(this);
		}
		else {
			RoleTableLocalServiceUtil.updateRoleTable(this);
		}
	}

}