/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package RoleManagementDB.model.impl;

import RoleManagementDB.model.UserRoleTable;

import RoleManagementDB.service.UserRoleTableLocalServiceUtil;

/**
 * The extended model base implementation for the UserRoleTable service. Represents a row in the &quot;UserRoleTable&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserRoleTableImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserRoleTableImpl
 * @see UserRoleTable
 * @generated
 */
public abstract class UserRoleTableBaseImpl
	extends UserRoleTableModelImpl implements UserRoleTable {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a user role table model instance should use the <code>UserRoleTable</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			UserRoleTableLocalServiceUtil.addUserRoleTable(this);
		}
		else {
			UserRoleTableLocalServiceUtil.updateUserRoleTable(this);
		}
	}

}