/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package RoleManagementDB.model.impl;

import RoleManagementDB.model.UserRoleTable;
import RoleManagementDB.model.UserRoleTableModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the UserRoleTable service. Represents a row in the &quot;UserRoleTable&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>UserRoleTableModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserRoleTableImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserRoleTableImpl
 * @generated
 */
public class UserRoleTableModelImpl
	extends BaseModelImpl<UserRoleTable> implements UserRoleTableModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a user role table model instance should use the <code>UserRoleTable</code> interface instead.
	 */
	public static final String TABLE_NAME = "UserRoleTable";

	public static final Object[][] TABLE_COLUMNS = {
		{"userRoleId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"roleId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("userRoleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("roleId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table UserRoleTable (userRoleId LONG not null primary key,userId LONG,roleId LONG)";

	public static final String TABLE_SQL_DROP = "drop table UserRoleTable";

	public static final String ORDER_BY_JPQL =
		" ORDER BY userRoleTable.userRoleId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY UserRoleTable.userRoleId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERROLEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public UserRoleTableModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _userRoleId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setUserRoleId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _userRoleId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return UserRoleTable.class;
	}

	@Override
	public String getModelClassName() {
		return UserRoleTable.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<UserRoleTable, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<UserRoleTable, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UserRoleTable, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((UserRoleTable)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<UserRoleTable, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<UserRoleTable, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(UserRoleTable)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<UserRoleTable, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<UserRoleTable, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<UserRoleTable, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<UserRoleTable, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<UserRoleTable, Object>>();

			attributeGetterFunctions.put(
				"userRoleId", UserRoleTable::getUserRoleId);
			attributeGetterFunctions.put("userId", UserRoleTable::getUserId);
			attributeGetterFunctions.put("roleId", UserRoleTable::getRoleId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<UserRoleTable, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<UserRoleTable, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<UserRoleTable, ?>>();

			attributeSetterBiConsumers.put(
				"userRoleId",
				(BiConsumer<UserRoleTable, Long>)UserRoleTable::setUserRoleId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<UserRoleTable, Long>)UserRoleTable::setUserId);
			attributeSetterBiConsumers.put(
				"roleId",
				(BiConsumer<UserRoleTable, Long>)UserRoleTable::setRoleId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getUserRoleId() {
		return _userRoleId;
	}

	@Override
	public void setUserRoleId(long userRoleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userRoleId = userRoleId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public long getRoleId() {
		return _roleId;
	}

	@Override
	public void setRoleId(long roleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_roleId = roleId;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, UserRoleTable.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public UserRoleTable toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, UserRoleTable>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		UserRoleTableImpl userRoleTableImpl = new UserRoleTableImpl();

		userRoleTableImpl.setUserRoleId(getUserRoleId());
		userRoleTableImpl.setUserId(getUserId());
		userRoleTableImpl.setRoleId(getRoleId());

		userRoleTableImpl.resetOriginalValues();

		return userRoleTableImpl;
	}

	@Override
	public UserRoleTable cloneWithOriginalValues() {
		UserRoleTableImpl userRoleTableImpl = new UserRoleTableImpl();

		userRoleTableImpl.setUserRoleId(
			this.<Long>getColumnOriginalValue("userRoleId"));
		userRoleTableImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		userRoleTableImpl.setRoleId(
			this.<Long>getColumnOriginalValue("roleId"));

		return userRoleTableImpl;
	}

	@Override
	public int compareTo(UserRoleTable userRoleTable) {
		long primaryKey = userRoleTable.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof UserRoleTable)) {
			return false;
		}

		UserRoleTable userRoleTable = (UserRoleTable)object;

		long primaryKey = userRoleTable.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<UserRoleTable> toCacheModel() {
		UserRoleTableCacheModel userRoleTableCacheModel =
			new UserRoleTableCacheModel();

		userRoleTableCacheModel.userRoleId = getUserRoleId();

		userRoleTableCacheModel.userId = getUserId();

		userRoleTableCacheModel.roleId = getRoleId();

		return userRoleTableCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<UserRoleTable, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<UserRoleTable, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<UserRoleTable, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((UserRoleTable)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, UserRoleTable>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					UserRoleTable.class, ModelWrapper.class);

	}

	private long _userRoleId;
	private long _userId;
	private long _roleId;

	public <T> T getColumnValue(String columnName) {
		Function<UserRoleTable, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((UserRoleTable)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("userRoleId", _userRoleId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("roleId", _roleId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("userRoleId", 1L);

		columnBitmasks.put("userId", 2L);

		columnBitmasks.put("roleId", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private UserRoleTable _escapedModel;

}