/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package OTP_DB.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SignUpOTP service. Represents a row in the &quot;fire_SignUpOTP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>OTP_DB.model.impl.SignUpOTPModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>OTP_DB.model.impl.SignUpOTPImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SignUpOTP
 * @generated
 */
@ProviderType
public interface SignUpOTPModel
	extends BaseModel<SignUpOTP>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sign up otp model instance should use the {@link SignUpOTP} interface instead.
	 */

	/**
	 * Returns the primary key of this sign up otp.
	 *
	 * @return the primary key of this sign up otp
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sign up otp.
	 *
	 * @param primaryKey the primary key of this sign up otp
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this sign up otp.
	 *
	 * @return the uuid of this sign up otp
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this sign up otp.
	 *
	 * @param uuid the uuid of this sign up otp
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the otp ID of this sign up otp.
	 *
	 * @return the otp ID of this sign up otp
	 */
	public long getOtpId();

	/**
	 * Sets the otp ID of this sign up otp.
	 *
	 * @param otpId the otp ID of this sign up otp
	 */
	public void setOtpId(long otpId);

	/**
	 * Returns the group ID of this sign up otp.
	 *
	 * @return the group ID of this sign up otp
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this sign up otp.
	 *
	 * @param groupId the group ID of this sign up otp
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this sign up otp.
	 *
	 * @return the company ID of this sign up otp
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this sign up otp.
	 *
	 * @param companyId the company ID of this sign up otp
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this sign up otp.
	 *
	 * @return the user ID of this sign up otp
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this sign up otp.
	 *
	 * @param userId the user ID of this sign up otp
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this sign up otp.
	 *
	 * @return the user uuid of this sign up otp
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this sign up otp.
	 *
	 * @param userUuid the user uuid of this sign up otp
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this sign up otp.
	 *
	 * @return the user name of this sign up otp
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this sign up otp.
	 *
	 * @param userName the user name of this sign up otp
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this sign up otp.
	 *
	 * @return the create date of this sign up otp
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this sign up otp.
	 *
	 * @param createDate the create date of this sign up otp
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this sign up otp.
	 *
	 * @return the modified date of this sign up otp
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this sign up otp.
	 *
	 * @param modifiedDate the modified date of this sign up otp
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the email_address of this sign up otp.
	 *
	 * @return the email_address of this sign up otp
	 */
	@AutoEscape
	public String getEmail_address();

	/**
	 * Sets the email_address of this sign up otp.
	 *
	 * @param email_address the email_address of this sign up otp
	 */
	public void setEmail_address(String email_address);

	/**
	 * Returns the otp of this sign up otp.
	 *
	 * @return the otp of this sign up otp
	 */
	@AutoEscape
	public String getOTP();

	/**
	 * Sets the otp of this sign up otp.
	 *
	 * @param OTP the otp of this sign up otp
	 */
	public void setOTP(String OTP);

	/**
	 * Returns the status of this sign up otp.
	 *
	 * @return the status of this sign up otp
	 */
	public boolean getStatus();

	/**
	 * Returns <code>true</code> if this sign up otp is status.
	 *
	 * @return <code>true</code> if this sign up otp is status; <code>false</code> otherwise
	 */
	public boolean isStatus();

	/**
	 * Sets whether this sign up otp is status.
	 *
	 * @param status the status of this sign up otp
	 */
	public void setStatus(boolean status);

	@Override
	public SignUpOTP cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}