/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package RoleManagementDB.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the RoleTable service. Represents a row in the &quot;fire_RoleTable&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>RoleManagementDB.model.impl.RoleTableModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>RoleManagementDB.model.impl.RoleTableImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RoleTable
 * @generated
 */
@ProviderType
public interface RoleTableModel
	extends BaseModel<RoleTable>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a role table model instance should use the {@link RoleTable} interface instead.
	 */

	/**
	 * Returns the primary key of this role table.
	 *
	 * @return the primary key of this role table
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this role table.
	 *
	 * @param primaryKey the primary key of this role table
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this role table.
	 *
	 * @return the uuid of this role table
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this role table.
	 *
	 * @param uuid the uuid of this role table
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the role ID of this role table.
	 *
	 * @return the role ID of this role table
	 */
	public long getRoleId();

	/**
	 * Sets the role ID of this role table.
	 *
	 * @param roleId the role ID of this role table
	 */
	public void setRoleId(long roleId);

	/**
	 * Returns the group ID of this role table.
	 *
	 * @return the group ID of this role table
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this role table.
	 *
	 * @param groupId the group ID of this role table
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this role table.
	 *
	 * @return the company ID of this role table
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this role table.
	 *
	 * @param companyId the company ID of this role table
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this role table.
	 *
	 * @return the user ID of this role table
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this role table.
	 *
	 * @param userId the user ID of this role table
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this role table.
	 *
	 * @return the user uuid of this role table
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this role table.
	 *
	 * @param userUuid the user uuid of this role table
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this role table.
	 *
	 * @return the user name of this role table
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this role table.
	 *
	 * @param userName the user name of this role table
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this role table.
	 *
	 * @return the create date of this role table
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this role table.
	 *
	 * @param createDate the create date of this role table
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this role table.
	 *
	 * @return the modified date of this role table
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this role table.
	 *
	 * @param modifiedDate the modified date of this role table
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the role name of this role table.
	 *
	 * @return the role name of this role table
	 */
	@AutoEscape
	public String getRoleName();

	/**
	 * Sets the role name of this role table.
	 *
	 * @param roleName the role name of this role table
	 */
	public void setRoleName(String roleName);

	/**
	 * Returns the description of this role table.
	 *
	 * @return the description of this role table
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this role table.
	 *
	 * @param description the description of this role table
	 */
	public void setDescription(String description);

	@Override
	public RoleTable cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}