/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package RoleManagementDB.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UserRoleTable service. Represents a row in the &quot;UserRoleTable&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>RoleManagementDB.model.impl.UserRoleTableModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>RoleManagementDB.model.impl.UserRoleTableImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserRoleTable
 * @generated
 */
@ProviderType
public interface UserRoleTableModel extends BaseModel<UserRoleTable> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user role table model instance should use the {@link UserRoleTable} interface instead.
	 */

	/**
	 * Returns the primary key of this user role table.
	 *
	 * @return the primary key of this user role table
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user role table.
	 *
	 * @param primaryKey the primary key of this user role table
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user role ID of this user role table.
	 *
	 * @return the user role ID of this user role table
	 */
	public long getUserRoleId();

	/**
	 * Sets the user role ID of this user role table.
	 *
	 * @param userRoleId the user role ID of this user role table
	 */
	public void setUserRoleId(long userRoleId);

	/**
	 * Returns the user ID of this user role table.
	 *
	 * @return the user ID of this user role table
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user role table.
	 *
	 * @param userId the user ID of this user role table
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user role table.
	 *
	 * @return the user uuid of this user role table
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user role table.
	 *
	 * @param userUuid the user uuid of this user role table
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the role ID of this user role table.
	 *
	 * @return the role ID of this user role table
	 */
	public long getRoleId();

	/**
	 * Sets the role ID of this user role table.
	 *
	 * @param roleId the role ID of this user role table
	 */
	public void setRoleId(long roleId);

	@Override
	public UserRoleTable cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}