/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package TicketMgmtDB.model.impl;

import TicketMgmtDB.model.TicketMgmt;
import TicketMgmtDB.model.TicketMgmtModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TicketMgmt service. Represents a row in the &quot;ATS_TicketMgmt&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TicketMgmtModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TicketMgmtImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TicketMgmtImpl
 * @generated
 */
public class TicketMgmtModelImpl
	extends BaseModelImpl<TicketMgmt> implements TicketMgmtModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ticket mgmt model instance should use the <code>TicketMgmt</code> interface instead.
	 */
	public static final String TABLE_NAME = "ATS_TicketMgmt";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"ticket_id", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"busNumber", Types.VARCHAR}, {"fromLocation", Types.VARCHAR},
		{"toLocation", Types.VARCHAR}, {"journeyDate", Types.TIMESTAMP},
		{"seatNumber", Types.INTEGER}, {"fareAmount", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ticket_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("busNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fromLocation", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("toLocation", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("journeyDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("seatNumber", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("fareAmount", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ATS_TicketMgmt (uuid_ VARCHAR(75) null,ticket_id LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,busNumber VARCHAR(75) null,fromLocation VARCHAR(75) null,toLocation VARCHAR(75) null,journeyDate DATE null,seatNumber INTEGER,fareAmount LONG)";

	public static final String TABLE_SQL_DROP = "drop table ATS_TicketMgmt";

	public static final String ORDER_BY_JPQL =
		" ORDER BY ticketMgmt.ticket_id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ATS_TicketMgmt.ticket_id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TICKET_ID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public TicketMgmtModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ticket_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTicket_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ticket_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TicketMgmt.class;
	}

	@Override
	public String getModelClassName() {
		return TicketMgmt.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TicketMgmt, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TicketMgmt, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TicketMgmt, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((TicketMgmt)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TicketMgmt, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TicketMgmt, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TicketMgmt)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TicketMgmt, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TicketMgmt, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<TicketMgmt, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<TicketMgmt, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<TicketMgmt, Object>>();

			attributeGetterFunctions.put("uuid", TicketMgmt::getUuid);
			attributeGetterFunctions.put("ticket_id", TicketMgmt::getTicket_id);
			attributeGetterFunctions.put("groupId", TicketMgmt::getGroupId);
			attributeGetterFunctions.put("companyId", TicketMgmt::getCompanyId);
			attributeGetterFunctions.put("userId", TicketMgmt::getUserId);
			attributeGetterFunctions.put("userName", TicketMgmt::getUserName);
			attributeGetterFunctions.put(
				"createDate", TicketMgmt::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", TicketMgmt::getModifiedDate);
			attributeGetterFunctions.put("busNumber", TicketMgmt::getBusNumber);
			attributeGetterFunctions.put(
				"fromLocation", TicketMgmt::getFromLocation);
			attributeGetterFunctions.put(
				"toLocation", TicketMgmt::getToLocation);
			attributeGetterFunctions.put(
				"journeyDate", TicketMgmt::getJourneyDate);
			attributeGetterFunctions.put(
				"seatNumber", TicketMgmt::getSeatNumber);
			attributeGetterFunctions.put(
				"fareAmount", TicketMgmt::getFareAmount);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<TicketMgmt, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<TicketMgmt, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<TicketMgmt, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<TicketMgmt, String>)TicketMgmt::setUuid);
			attributeSetterBiConsumers.put(
				"ticket_id",
				(BiConsumer<TicketMgmt, Long>)TicketMgmt::setTicket_id);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<TicketMgmt, Long>)TicketMgmt::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<TicketMgmt, Long>)TicketMgmt::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<TicketMgmt, Long>)TicketMgmt::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<TicketMgmt, String>)TicketMgmt::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<TicketMgmt, Date>)TicketMgmt::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<TicketMgmt, Date>)TicketMgmt::setModifiedDate);
			attributeSetterBiConsumers.put(
				"busNumber",
				(BiConsumer<TicketMgmt, String>)TicketMgmt::setBusNumber);
			attributeSetterBiConsumers.put(
				"fromLocation",
				(BiConsumer<TicketMgmt, String>)TicketMgmt::setFromLocation);
			attributeSetterBiConsumers.put(
				"toLocation",
				(BiConsumer<TicketMgmt, String>)TicketMgmt::setToLocation);
			attributeSetterBiConsumers.put(
				"journeyDate",
				(BiConsumer<TicketMgmt, Date>)TicketMgmt::setJourneyDate);
			attributeSetterBiConsumers.put(
				"seatNumber",
				(BiConsumer<TicketMgmt, Integer>)TicketMgmt::setSeatNumber);
			attributeSetterBiConsumers.put(
				"fareAmount",
				(BiConsumer<TicketMgmt, Long>)TicketMgmt::setFareAmount);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getTicket_id() {
		return _ticket_id;
	}

	@Override
	public void setTicket_id(long ticket_id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ticket_id = ticket_id;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getBusNumber() {
		if (_busNumber == null) {
			return "";
		}
		else {
			return _busNumber;
		}
	}

	@Override
	public void setBusNumber(String busNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_busNumber = busNumber;
	}

	@Override
	public String getFromLocation() {
		if (_fromLocation == null) {
			return "";
		}
		else {
			return _fromLocation;
		}
	}

	@Override
	public void setFromLocation(String fromLocation) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fromLocation = fromLocation;
	}

	@Override
	public String getToLocation() {
		if (_toLocation == null) {
			return "";
		}
		else {
			return _toLocation;
		}
	}

	@Override
	public void setToLocation(String toLocation) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_toLocation = toLocation;
	}

	@Override
	public Date getJourneyDate() {
		return _journeyDate;
	}

	@Override
	public void setJourneyDate(Date journeyDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_journeyDate = journeyDate;
	}

	@Override
	public int getSeatNumber() {
		return _seatNumber;
	}

	@Override
	public void setSeatNumber(int seatNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_seatNumber = seatNumber;
	}

	@Override
	public Long getFareAmount() {
		return _fareAmount;
	}

	@Override
	public void setFareAmount(Long fareAmount) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fareAmount = fareAmount;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(TicketMgmt.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), TicketMgmt.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TicketMgmt toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TicketMgmt>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TicketMgmtImpl ticketMgmtImpl = new TicketMgmtImpl();

		ticketMgmtImpl.setUuid(getUuid());
		ticketMgmtImpl.setTicket_id(getTicket_id());
		ticketMgmtImpl.setGroupId(getGroupId());
		ticketMgmtImpl.setCompanyId(getCompanyId());
		ticketMgmtImpl.setUserId(getUserId());
		ticketMgmtImpl.setUserName(getUserName());
		ticketMgmtImpl.setCreateDate(getCreateDate());
		ticketMgmtImpl.setModifiedDate(getModifiedDate());
		ticketMgmtImpl.setBusNumber(getBusNumber());
		ticketMgmtImpl.setFromLocation(getFromLocation());
		ticketMgmtImpl.setToLocation(getToLocation());
		ticketMgmtImpl.setJourneyDate(getJourneyDate());
		ticketMgmtImpl.setSeatNumber(getSeatNumber());
		ticketMgmtImpl.setFareAmount(getFareAmount());

		ticketMgmtImpl.resetOriginalValues();

		return ticketMgmtImpl;
	}

	@Override
	public TicketMgmt cloneWithOriginalValues() {
		TicketMgmtImpl ticketMgmtImpl = new TicketMgmtImpl();

		ticketMgmtImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		ticketMgmtImpl.setTicket_id(
			this.<Long>getColumnOriginalValue("ticket_id"));
		ticketMgmtImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		ticketMgmtImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		ticketMgmtImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		ticketMgmtImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		ticketMgmtImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		ticketMgmtImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		ticketMgmtImpl.setBusNumber(
			this.<String>getColumnOriginalValue("busNumber"));
		ticketMgmtImpl.setFromLocation(
			this.<String>getColumnOriginalValue("fromLocation"));
		ticketMgmtImpl.setToLocation(
			this.<String>getColumnOriginalValue("toLocation"));
		ticketMgmtImpl.setJourneyDate(
			this.<Date>getColumnOriginalValue("journeyDate"));
		ticketMgmtImpl.setSeatNumber(
			this.<Integer>getColumnOriginalValue("seatNumber"));
		ticketMgmtImpl.setFareAmount(
			this.<Long>getColumnOriginalValue("fareAmount"));

		return ticketMgmtImpl;
	}

	@Override
	public int compareTo(TicketMgmt ticketMgmt) {
		long primaryKey = ticketMgmt.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TicketMgmt)) {
			return false;
		}

		TicketMgmt ticketMgmt = (TicketMgmt)object;

		long primaryKey = ticketMgmt.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<TicketMgmt> toCacheModel() {
		TicketMgmtCacheModel ticketMgmtCacheModel = new TicketMgmtCacheModel();

		ticketMgmtCacheModel.uuid = getUuid();

		String uuid = ticketMgmtCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			ticketMgmtCacheModel.uuid = null;
		}

		ticketMgmtCacheModel.ticket_id = getTicket_id();

		ticketMgmtCacheModel.groupId = getGroupId();

		ticketMgmtCacheModel.companyId = getCompanyId();

		ticketMgmtCacheModel.userId = getUserId();

		ticketMgmtCacheModel.userName = getUserName();

		String userName = ticketMgmtCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			ticketMgmtCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			ticketMgmtCacheModel.createDate = createDate.getTime();
		}
		else {
			ticketMgmtCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			ticketMgmtCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			ticketMgmtCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		ticketMgmtCacheModel.busNumber = getBusNumber();

		String busNumber = ticketMgmtCacheModel.busNumber;

		if ((busNumber != null) && (busNumber.length() == 0)) {
			ticketMgmtCacheModel.busNumber = null;
		}

		ticketMgmtCacheModel.fromLocation = getFromLocation();

		String fromLocation = ticketMgmtCacheModel.fromLocation;

		if ((fromLocation != null) && (fromLocation.length() == 0)) {
			ticketMgmtCacheModel.fromLocation = null;
		}

		ticketMgmtCacheModel.toLocation = getToLocation();

		String toLocation = ticketMgmtCacheModel.toLocation;

		if ((toLocation != null) && (toLocation.length() == 0)) {
			ticketMgmtCacheModel.toLocation = null;
		}

		Date journeyDate = getJourneyDate();

		if (journeyDate != null) {
			ticketMgmtCacheModel.journeyDate = journeyDate.getTime();
		}
		else {
			ticketMgmtCacheModel.journeyDate = Long.MIN_VALUE;
		}

		ticketMgmtCacheModel.seatNumber = getSeatNumber();

		Long fareAmount = getFareAmount();

		if (fareAmount != null) {
			ticketMgmtCacheModel.fareAmount = fareAmount;
		}

		return ticketMgmtCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TicketMgmt, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TicketMgmt, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TicketMgmt, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((TicketMgmt)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TicketMgmt>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					TicketMgmt.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _ticket_id;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _busNumber;
	private String _fromLocation;
	private String _toLocation;
	private Date _journeyDate;
	private int _seatNumber;
	private Long _fareAmount;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<TicketMgmt, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((TicketMgmt)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("ticket_id", _ticket_id);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("busNumber", _busNumber);
		_columnOriginalValues.put("fromLocation", _fromLocation);
		_columnOriginalValues.put("toLocation", _toLocation);
		_columnOriginalValues.put("journeyDate", _journeyDate);
		_columnOriginalValues.put("seatNumber", _seatNumber);
		_columnOriginalValues.put("fareAmount", _fareAmount);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("ticket_id", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("busNumber", 256L);

		columnBitmasks.put("fromLocation", 512L);

		columnBitmasks.put("toLocation", 1024L);

		columnBitmasks.put("journeyDate", 2048L);

		columnBitmasks.put("seatNumber", 4096L);

		columnBitmasks.put("fareAmount", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private TicketMgmt _escapedModel;

}