/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package RequestManagementDB.model.impl;

import RequestManagementDB.model.EmrgcyRequest;
import RequestManagementDB.model.EmrgcyRequestModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EmrgcyRequest service. Represents a row in the &quot;Fire_EmrgcyRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EmrgcyRequestModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmrgcyRequestImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmrgcyRequestImpl
 * @generated
 */
@JSON(strict = true)
public class EmrgcyRequestModelImpl
	extends BaseModelImpl<EmrgcyRequest> implements EmrgcyRequestModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a emrgcy request model instance should use the <code>EmrgcyRequest</code> interface instead.
	 */
	public static final String TABLE_NAME = "Fire_EmrgcyRequest";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"requestId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"title", Types.VARCHAR},
		{"description", Types.VARCHAR}, {"location", Types.VARCHAR},
		{"status", Types.VARCHAR}, {"assignedTeam", Types.VARCHAR},
		{"requesterUserId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("requestId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("location", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("assignedTeam", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("requesterUserId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Fire_EmrgcyRequest (uuid_ VARCHAR(75) null,requestId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,title VARCHAR(75) null,description VARCHAR(75) null,location VARCHAR(75) null,status VARCHAR(75) null,assignedTeam VARCHAR(75) null,requesterUserId LONG)";

	public static final String TABLE_SQL_DROP = "drop table Fire_EmrgcyRequest";

	public static final String ORDER_BY_JPQL =
		" ORDER BY emrgcyRequest.requestId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Fire_EmrgcyRequest.requestId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long REQUESTID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public EmrgcyRequestModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _requestId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRequestId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _requestId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmrgcyRequest.class;
	}

	@Override
	public String getModelClassName() {
		return EmrgcyRequest.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EmrgcyRequest, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EmrgcyRequest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmrgcyRequest, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EmrgcyRequest)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EmrgcyRequest, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EmrgcyRequest, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EmrgcyRequest)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EmrgcyRequest, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EmrgcyRequest, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<EmrgcyRequest, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<EmrgcyRequest, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<EmrgcyRequest, Object>>();

			attributeGetterFunctions.put("uuid", EmrgcyRequest::getUuid);
			attributeGetterFunctions.put(
				"requestId", EmrgcyRequest::getRequestId);
			attributeGetterFunctions.put(
				"companyId", EmrgcyRequest::getCompanyId);
			attributeGetterFunctions.put("userId", EmrgcyRequest::getUserId);
			attributeGetterFunctions.put(
				"userName", EmrgcyRequest::getUserName);
			attributeGetterFunctions.put(
				"createDate", EmrgcyRequest::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", EmrgcyRequest::getModifiedDate);
			attributeGetterFunctions.put("title", EmrgcyRequest::getTitle);
			attributeGetterFunctions.put(
				"description", EmrgcyRequest::getDescription);
			attributeGetterFunctions.put(
				"location", EmrgcyRequest::getLocation);
			attributeGetterFunctions.put("status", EmrgcyRequest::getStatus);
			attributeGetterFunctions.put(
				"assignedTeam", EmrgcyRequest::getAssignedTeam);
			attributeGetterFunctions.put(
				"requesterUserId", EmrgcyRequest::getRequesterUserId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<EmrgcyRequest, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<EmrgcyRequest, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<EmrgcyRequest, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<EmrgcyRequest, String>)EmrgcyRequest::setUuid);
			attributeSetterBiConsumers.put(
				"requestId",
				(BiConsumer<EmrgcyRequest, Long>)EmrgcyRequest::setRequestId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<EmrgcyRequest, Long>)EmrgcyRequest::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<EmrgcyRequest, Long>)EmrgcyRequest::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<EmrgcyRequest, String>)EmrgcyRequest::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<EmrgcyRequest, Date>)EmrgcyRequest::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<EmrgcyRequest, Date>)
					EmrgcyRequest::setModifiedDate);
			attributeSetterBiConsumers.put(
				"title",
				(BiConsumer<EmrgcyRequest, String>)EmrgcyRequest::setTitle);
			attributeSetterBiConsumers.put(
				"description",
				(BiConsumer<EmrgcyRequest, String>)
					EmrgcyRequest::setDescription);
			attributeSetterBiConsumers.put(
				"location",
				(BiConsumer<EmrgcyRequest, String>)EmrgcyRequest::setLocation);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<EmrgcyRequest, String>)EmrgcyRequest::setStatus);
			attributeSetterBiConsumers.put(
				"assignedTeam",
				(BiConsumer<EmrgcyRequest, String>)
					EmrgcyRequest::setAssignedTeam);
			attributeSetterBiConsumers.put(
				"requesterUserId",
				(BiConsumer<EmrgcyRequest, Long>)
					EmrgcyRequest::setRequesterUserId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getRequestId() {
		return _requestId;
	}

	@Override
	public void setRequestId(long requestId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_requestId = requestId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_title = title;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@JSON
	@Override
	public String getLocation() {
		if (_location == null) {
			return "";
		}
		else {
			return _location;
		}
	}

	@Override
	public void setLocation(String location) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_location = location;
	}

	@JSON
	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@JSON
	@Override
	public String getAssignedTeam() {
		if (_assignedTeam == null) {
			return "";
		}
		else {
			return _assignedTeam;
		}
	}

	@Override
	public void setAssignedTeam(String assignedTeam) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_assignedTeam = assignedTeam;
	}

	@JSON
	@Override
	public long getRequesterUserId() {
		return _requesterUserId;
	}

	@Override
	public void setRequesterUserId(long requesterUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_requesterUserId = requesterUserId;
	}

	@Override
	public String getRequesterUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getRequesterUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setRequesterUserUuid(String requesterUserUuid) {
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(EmrgcyRequest.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EmrgcyRequest.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EmrgcyRequest toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EmrgcyRequest>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmrgcyRequestImpl emrgcyRequestImpl = new EmrgcyRequestImpl();

		emrgcyRequestImpl.setUuid(getUuid());
		emrgcyRequestImpl.setRequestId(getRequestId());
		emrgcyRequestImpl.setCompanyId(getCompanyId());
		emrgcyRequestImpl.setUserId(getUserId());
		emrgcyRequestImpl.setUserName(getUserName());
		emrgcyRequestImpl.setCreateDate(getCreateDate());
		emrgcyRequestImpl.setModifiedDate(getModifiedDate());
		emrgcyRequestImpl.setTitle(getTitle());
		emrgcyRequestImpl.setDescription(getDescription());
		emrgcyRequestImpl.setLocation(getLocation());
		emrgcyRequestImpl.setStatus(getStatus());
		emrgcyRequestImpl.setAssignedTeam(getAssignedTeam());
		emrgcyRequestImpl.setRequesterUserId(getRequesterUserId());

		emrgcyRequestImpl.resetOriginalValues();

		return emrgcyRequestImpl;
	}

	@Override
	public EmrgcyRequest cloneWithOriginalValues() {
		EmrgcyRequestImpl emrgcyRequestImpl = new EmrgcyRequestImpl();

		emrgcyRequestImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		emrgcyRequestImpl.setRequestId(
			this.<Long>getColumnOriginalValue("requestId"));
		emrgcyRequestImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		emrgcyRequestImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		emrgcyRequestImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		emrgcyRequestImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		emrgcyRequestImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		emrgcyRequestImpl.setTitle(
			this.<String>getColumnOriginalValue("title"));
		emrgcyRequestImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		emrgcyRequestImpl.setLocation(
			this.<String>getColumnOriginalValue("location"));
		emrgcyRequestImpl.setStatus(
			this.<String>getColumnOriginalValue("status"));
		emrgcyRequestImpl.setAssignedTeam(
			this.<String>getColumnOriginalValue("assignedTeam"));
		emrgcyRequestImpl.setRequesterUserId(
			this.<Long>getColumnOriginalValue("requesterUserId"));

		return emrgcyRequestImpl;
	}

	@Override
	public int compareTo(EmrgcyRequest emrgcyRequest) {
		long primaryKey = emrgcyRequest.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EmrgcyRequest)) {
			return false;
		}

		EmrgcyRequest emrgcyRequest = (EmrgcyRequest)object;

		long primaryKey = emrgcyRequest.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EmrgcyRequest> toCacheModel() {
		EmrgcyRequestCacheModel emrgcyRequestCacheModel =
			new EmrgcyRequestCacheModel();

		emrgcyRequestCacheModel.uuid = getUuid();

		String uuid = emrgcyRequestCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			emrgcyRequestCacheModel.uuid = null;
		}

		emrgcyRequestCacheModel.requestId = getRequestId();

		emrgcyRequestCacheModel.companyId = getCompanyId();

		emrgcyRequestCacheModel.userId = getUserId();

		emrgcyRequestCacheModel.userName = getUserName();

		String userName = emrgcyRequestCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			emrgcyRequestCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			emrgcyRequestCacheModel.createDate = createDate.getTime();
		}
		else {
			emrgcyRequestCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			emrgcyRequestCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			emrgcyRequestCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		emrgcyRequestCacheModel.title = getTitle();

		String title = emrgcyRequestCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			emrgcyRequestCacheModel.title = null;
		}

		emrgcyRequestCacheModel.description = getDescription();

		String description = emrgcyRequestCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			emrgcyRequestCacheModel.description = null;
		}

		emrgcyRequestCacheModel.location = getLocation();

		String location = emrgcyRequestCacheModel.location;

		if ((location != null) && (location.length() == 0)) {
			emrgcyRequestCacheModel.location = null;
		}

		emrgcyRequestCacheModel.status = getStatus();

		String status = emrgcyRequestCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			emrgcyRequestCacheModel.status = null;
		}

		emrgcyRequestCacheModel.assignedTeam = getAssignedTeam();

		String assignedTeam = emrgcyRequestCacheModel.assignedTeam;

		if ((assignedTeam != null) && (assignedTeam.length() == 0)) {
			emrgcyRequestCacheModel.assignedTeam = null;
		}

		emrgcyRequestCacheModel.requesterUserId = getRequesterUserId();

		return emrgcyRequestCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EmrgcyRequest, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EmrgcyRequest, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmrgcyRequest, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((EmrgcyRequest)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EmrgcyRequest>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					EmrgcyRequest.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _requestId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _title;
	private String _description;
	private String _location;
	private String _status;
	private String _assignedTeam;
	private long _requesterUserId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<EmrgcyRequest, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((EmrgcyRequest)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("requestId", _requestId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("title", _title);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("location", _location);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("assignedTeam", _assignedTeam);
		_columnOriginalValues.put("requesterUserId", _requesterUserId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("requestId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("title", 128L);

		columnBitmasks.put("description", 256L);

		columnBitmasks.put("location", 512L);

		columnBitmasks.put("status", 1024L);

		columnBitmasks.put("assignedTeam", 2048L);

		columnBitmasks.put("requesterUserId", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private EmrgcyRequest _escapedModel;

}