/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package OTP_DB.model.impl;

import OTP_DB.model.SignUpOTP;

import OTP_DB.service.SignUpOTPLocalServiceUtil;

/**
 * The extended model base implementation for the SignUpOTP service. Represents a row in the &quot;fire_SignUpOTP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SignUpOTPImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SignUpOTPImpl
 * @see SignUpOTP
 * @generated
 */
public abstract class SignUpOTPBaseImpl
	extends SignUpOTPModelImpl implements SignUpOTP {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sign up otp model instance should use the <code>SignUpOTP</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			SignUpOTPLocalServiceUtil.addSignUpOTP(this);
		}
		else {
			SignUpOTPLocalServiceUtil.updateSignUpOTP(this);
		}
	}

}