/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package EmergencyRequestDB.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EmergencyRequest service. Represents a row in the &quot;Fire_EmergencyRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>EmergencyRequestDB.model.impl.EmergencyRequestModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>EmergencyRequestDB.model.impl.EmergencyRequestImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmergencyRequest
 * @generated
 */
@ProviderType
public interface EmergencyRequestModel
	extends BaseModel<EmergencyRequest>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a emergency request model instance should use the {@link EmergencyRequest} interface instead.
	 */

	/**
	 * Returns the primary key of this emergency request.
	 *
	 * @return the primary key of this emergency request
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this emergency request.
	 *
	 * @param primaryKey the primary key of this emergency request
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this emergency request.
	 *
	 * @return the uuid of this emergency request
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this emergency request.
	 *
	 * @param uuid the uuid of this emergency request
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the request ID of this emergency request.
	 *
	 * @return the request ID of this emergency request
	 */
	public long getRequestId();

	/**
	 * Sets the request ID of this emergency request.
	 *
	 * @param requestId the request ID of this emergency request
	 */
	public void setRequestId(long requestId);

	/**
	 * Returns the group ID of this emergency request.
	 *
	 * @return the group ID of this emergency request
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this emergency request.
	 *
	 * @param groupId the group ID of this emergency request
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this emergency request.
	 *
	 * @return the company ID of this emergency request
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this emergency request.
	 *
	 * @param companyId the company ID of this emergency request
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this emergency request.
	 *
	 * @return the user ID of this emergency request
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this emergency request.
	 *
	 * @param userId the user ID of this emergency request
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this emergency request.
	 *
	 * @return the user uuid of this emergency request
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this emergency request.
	 *
	 * @param userUuid the user uuid of this emergency request
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this emergency request.
	 *
	 * @return the user name of this emergency request
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this emergency request.
	 *
	 * @param userName the user name of this emergency request
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this emergency request.
	 *
	 * @return the create date of this emergency request
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this emergency request.
	 *
	 * @param createDate the create date of this emergency request
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this emergency request.
	 *
	 * @return the modified date of this emergency request
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this emergency request.
	 *
	 * @param modifiedDate the modified date of this emergency request
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the request title of this emergency request.
	 *
	 * @return the request title of this emergency request
	 */
	@AutoEscape
	public String getRequestTitle();

	/**
	 * Sets the request title of this emergency request.
	 *
	 * @param requestTitle the request title of this emergency request
	 */
	public void setRequestTitle(String requestTitle);

	/**
	 * Returns the description of this emergency request.
	 *
	 * @return the description of this emergency request
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this emergency request.
	 *
	 * @param description the description of this emergency request
	 */
	public void setDescription(String description);

	/**
	 * Returns the location of this emergency request.
	 *
	 * @return the location of this emergency request
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this emergency request.
	 *
	 * @param location the location of this emergency request
	 */
	public void setLocation(String location);

	/**
	 * Returns the exact address of this emergency request.
	 *
	 * @return the exact address of this emergency request
	 */
	@AutoEscape
	public String getExactAddress();

	/**
	 * Sets the exact address of this emergency request.
	 *
	 * @param exactAddress the exact address of this emergency request
	 */
	public void setExactAddress(String exactAddress);

	/**
	 * Returns the attachment path of this emergency request.
	 *
	 * @return the attachment path of this emergency request
	 */
	@AutoEscape
	public String getAttachmentPath();

	/**
	 * Sets the attachment path of this emergency request.
	 *
	 * @param attachmentPath the attachment path of this emergency request
	 */
	public void setAttachmentPath(String attachmentPath);

	/**
	 * Returns the status of this emergency request.
	 *
	 * @return the status of this emergency request
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this emergency request.
	 *
	 * @param status the status of this emergency request
	 */
	public void setStatus(String status);

	/**
	 * Returns the allocated team ID of this emergency request.
	 *
	 * @return the allocated team ID of this emergency request
	 */
	public long getAllocatedTeamId();

	/**
	 * Sets the allocated team ID of this emergency request.
	 *
	 * @param allocatedTeamId the allocated team ID of this emergency request
	 */
	public void setAllocatedTeamId(long allocatedTeamId);

	@Override
	public EmergencyRequest cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}